In [3]:
import numpy as np
a=[]
for i in range (21):
    a.append(i)
vector=np.array(a)
print(vector)
vector=np.where(((vector>=9) & (vector<=15)),-vector,vector)
print (vector)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [9]:
r=int(input("entrer the rowsize : "))
c=int(input("enter the column size : "))
m=[]
for i in range (r) :
    row=[]
    for j in range (c) :
        a=int(input())
        row.append(a)
    m.append(row)
print(m)
sum=np.sum(m)
print("Sum = ",sum)
rowsum=np.sum(m,1)
print("Row Sum = ",rowsum)
colsum=np.sum(m,0)
print("Column Sum = ",colsum)

entrer the rowsize : 3
enter the column size : 3
1
2
3
4
5
6
7
8
9
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Sum =  45
Row Sum =  [ 6 15 24]
Column Sum =  [12 15 18]


In [11]:
r=int(input("entrer the rowsize : "))
c=int(input("enter the column size : "))
m=[]
for i in range (r) :
    row=[]
    for j in range (c) :
        a=int(input())
        row.append(a)
    m.append(row)
print(m)
np.savetxt('array.txt',m,fmt='%d')
loadarray=np.loadtxt('array.txt',int)
print(loadarray)

entrer the rowsize : 3
enter the column size : 3
3
4
5
6
7
8
9
7
55
[[3, 4, 5], [6, 7, 8], [9, 7, 55]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9  7 55]]


r=int(input("enter the rowsize : "))
c=int(input("enter the column size : "))
m=[]
for i in range (r) :
    row=[]
    for j in range (c) :
        a=int(input())
        row.append(a)
    m.append(row)
print(m)
ro=int(input("entrer the rowsize : "))
co=int(input("enter the column size : "))
mat=[]
for i in range (r) :
    row=[]
    for j in range (c) :
        b=int(input())
        row.append(a)
    mat.append(row)
print(mat)

In [13]:
r=int(input("entrer the rowsize : "))
c=int(input("enter the column size : "))
m=[]
for i in range (r) :
    row=[]
    for j in range (c) :
        a=int(input())
        row.append(a)
    m.append(row)
print(m)
ro=int(input("entrer the rowsize : "))
co=int(input("enter the column size : "))
mat=[]
for i in range (r) :
    row=[]
    for j in range (c) :
        b=int(input())
        row.append(b)
    mat.append(row)
print(mat)
c=np.equal(m,mat)
print(c)

entrer the rowsize : 2
enter the column size : 2
1
2
3
4
[[1, 2], [3, 4]]
entrer the rowsize : 2
enter the column size : 2
5
6
7
8
[[5, 6], [7, 8]]
[[False False]
 [False False]]


In [22]:
a=np.random.randint(0,100,size=(4,4))
print("Original array",a)
a[[0,3]]=a[[3,0]]
print("After swapping ",a)

Original array [[33 25 23 20]
 [ 5 61 82 97]
 [10 10 85 35]
 [ 2 96 97 47]]
After swapping  [[ 2 96 97 47]
 [ 5 61 82 97]
 [10 10 85 35]
 [33 25 23 20]]


In [24]:
a=np.random.randint(1,10,size=(2,2))
b=np.random.randint(1,10,size=(2,2))
print(a)
print(b)
res=a*b
print(res)

[[9 5]
 [8 2]]
[[1 5]
 [6 9]]
[[ 9 25]
 [48 18]]


In [25]:
r=int(input("entrer the rowsize : "))
c=int(input("enter the column size : "))
m=[]
for i in range (r) :
    row=[]
    for j in range (c) :
        a=int(input())
        row.append(a)
    m.append(row)
print(m)
ro=int(input("entrer the rowsize : "))
co=int(input("enter the column size : "))
mat=[]
for i in range (r) :
    row=[]
    for j in range (c) :
        b=int(input())
        row.append(b)
    mat.append(row)
print(mat)
res=m*mat
print(res)

entrer the rowsize : 2
enter the column size : 2
1
2
3
4
[[1, 2], [3, 4]]
entrer the rowsize : 2
enter the column size : 2
5
6
7
8
[[5, 6], [7, 8]]


TypeError: can't multiply sequence by non-int of type 'list'