In [8]:
import numpy as np
m1=np.array([[1,2,3],[5,6,7]])
print(m1)
m2=np.array([[4,7,9],[3,0,8],[1,4,9]])
print(m2)




[[1 2 3]
 [5 6 7]]
[[4 7 9]
 [3 0 8]
 [1 4 9]]


In [7]:
c=np.dot(m1,m2)
print(c)

[[ 13  19  52]
 [ 45  63 156]]


In [2]:
t1=np.transpose(m1)
t2=np.transpose(m2)
print(t1)
print(t2)



NameError: name 'np' is not defined

In [10]:
print(m1.flatten())

[1 2 3 5 6 7]


In [11]:
mtr=[]
for i in range (2) :
    row=[]
    for j in range (2) :
        a=int(input())
        row.append(a)
    mtr.append(row)
print(mtr)

4
5
6
7
[[4, 5], [6, 7]]


In [16]:
r=int(input("entrer the rowsize : "))
c=int(input("enter the column size : "))
m=[]
for i in range (r) :
    row=[]
    for j in range (c) :
        a=int(input())
        row.append(a)
    m.append(row)
print(m)

entrer the rowsize : 3
enter the column size : 2
4
5
6
7
8
9
[[4, 5], [6, 7], [8, 9]]


In [7]:
r=int(input("entrer the rowsize : "))
c=int(input("enter the column size : "))
a=list(map(int,input().split()))
mt=np.array(a).reshape(r,c)
print(mt)

entrer the rowsize : 2
enter the column size : 2
1 2 3 4
[[1 2]
 [3 4]]


In [8]:
import numpy as np
b=np.linalg.inv(mt)
print(b)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [9]:
r=np.linalg.det(mt)
print(r)

-2.0000000000000004


In [10]:
print(mt.trace())

5


In [11]:
print(np.linalg.matrix_rank(mt))

2


In [12]:
print(np.linalg.eig(mt))

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
