In [1]:
10+5

15

In [2]:
s=10+5
s

15

In [3]:
a=1+1
b=2-2
a
b

0

In [4]:
print("hello")

hello


In [5]:
a=5
b=10
print(c=b/a)

TypeError: 'c' is an invalid keyword argument for print()

In [8]:
a=5
b=10
c=b/a
print(c)

2.0


In [7]:
a=5
b=10
c=a*b
print(c)

50


In [28]:
import numpy as np
a=np.array([1,2,3])
print(a)
b=np.array([[1,2,3],[4,5,6]])
print(b)
print (a.shape)
print(b.shape)
c=b.reshape(3,2)
print(c)
x=np.arange(10)
print(x)
x=np.arange(1,24,2,dtype=float)
print(x)

[1 2 3]
[[1 2 3]
 [4 5 6]]
(3,)
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[0 1 2 3 4 5 6 7 8 9]
[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21. 23.]


In [37]:
import numpy as np
a=np.array([1,2,3])
print(a)
b=np.array([4,5,7])
print(b)
c=np.less(a,b)
print(c)
c=np.less_equal(a,b)
print(c)
c=np.greater(a,b)
print(c)
c=np.greater_equal(b,a)
print(c)
c=np.equal(b,a)
print(c)

[1 2 3]
[4 5 7]
[ True  True  True]
[ True  True  True]
[False False False]
[ True  True  True]
[False False False]


In [38]:
import numpy as np
x=np.arange(50,90,2)
print(x)

[50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88]


In [40]:

import numpy as np
x=np.identity(4,dtype=int)
print(x)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [41]:
#5X5 zero matrix with elements on the main diagonal 1 2 3 4 5
import numpy as np
x=np.diag([1,2,3,4,5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
